import { Data } from "@/components/Table/type";

export const mockData: Data[] = [
  {
    rut: "40.027.012-12",
    publicName: "Juan Rodriguez",
    email: "Juan.Rodriguez@sinacofi.com",
    password: "123456789",
    validity: "Indefinido",
    group: "03 - Tratador de Mensajes",
    institution: "0020 - Banco Itaú",
    area: "05",
    status: 3,
    actions: "test1",
  },
  {
    rut: "40.027.012-12",
    publicName: "Roberto Diaz",
    email: "Roberto.Diaz@sinacofi.com",
    password: "123456789",
    validity: "Indefinido",
    group: "05 - Administrador Instituciones, 03 - Tratador de Mensajes",
    institution: "0020 - Banco Itaú",
    area: "05",
    status: 1,
    actions: "test2",
  },
  {
    rut: "23.482.223-1",
    publicName: "Federico Jimenez",
    email: "Federico.Jimenez@sinacofi.com",
    password: "123456789",
    validity: "Indefinido",
    group: "05 - Administrador Instituciones",
    institution: "string",
    area: "05",
    status: 3,
    actions: "test3",
  },
  {
    rut: "34.482.232-5",
    publicName: "Felipe Cardenas",
    email: "Felipe.Cardenas@sinacofi.com",
    password: "123456789",
    validity: "Indefinido",
    group: "05 - Administrador Instituciones",
    institution: "0020 - Banco Itaú",
    area: "05",
    status: 3,
    actions: "test4",
  },
  {
    rut: "21.234.223-4",
    publicName: "Julia Perez",
    email: "Julia.Perez@sinacofi.com",
    password: "123456789",
    validity: "Indefinido",
    group: "07 - Todas RIH",
    institution: "0032 - HSBC",
    area: "05",
    status: 3,
    actions: "test5",
  },
  {
    rut: "26.432.223-3",
    publicName: "Laura Lopez",
    email: "Laura.Lopez@sinacofi.com",
    password: "123456789",
    validity: "Indefinido",
    group: "03 - Tratador de Mensajes",
    institution: "0017 - Falabella",
    area: "05",
    status: 3,
    actions: "test6",
  },
  {
    rut: "12.537.223-5",
    publicName: "Ramiro Montaner",
    email: "Ramiro.Montaner@sinacofi.com",
    password: "123456789",
    validity: "Indefinido",
    group: "03 - Tratador de Mensajes",
    institution: "0022 - JP Morgan",
    area: "05",
    status: 3,
    actions: "test7",
  },
  {
    rut: "27.632.223-4",
    publicName: "Monica Smith",
    email: "Monica.Smith@sinacofi.com",
    password: "123456789",
    validity: "Indefinido",
    group: "03 - Tratador de Mensajes",
    institution: "0022 - JP Morgan",
    area: "05",
    status: 3,
    actions: "test8",
  },
];
