version: "3.8"
services:
  webapp:
    build: .
    image: sinacofi_web
    container_name: sinacofi_web
    restart: always
    env_file:
      - .env
    ports:
      - "8081:3000"
    volumes:
      - ${LOG_PATH:-./logs/}:/var/log
