export const areas = [{
    id: '35',
    name: 'OPERADOR',
    description: 'MESA DE DINERO',
    distributionPath: '',
    pathPams: '',
    pathSams: '',
    ftiiCode: '',
    conectivityType: 'Browser',
    institutionCode: '',
    isActive: true
},{
    id: '82',
    name: 'ESTADISTICAS',
    description: 'ETL',
    distributionPath: '',
    pathPams: '',
    pathSams: '',
    ftiiCode: '',
    conectivityType: 'Browser',
    institutionCode: '',
    isActive: true
},
{
    id: '83',
    name: 'CAMARAS',
    description: 'LBTR',
    distributionPath: '',
    pathPams: '',
    pathSams: '',
    ftiiCode: '',
    conectivityType: 'Browser',
    institutionCode: '',
    isActive: true
},
{
    id: '81',
    name: 'AMDS',
    description: 'AMDS',
    distributionPath: '',
    pathPams: '',
    pathSams: '',
    ftiiCode: '',
    conectivityType: 'Browser',
    institutionCode: '',
    isActive: true
},
{
    id: '5',
    name: 'AREA TID',
    description: 'AREA TID',
    distributionPath: '',
    pathPams: '',
    pathSams: '',
    ftiiCode: '',
    conectivityType: 'Browser',
    institutionCode: '',
    isActive: true
},
{
    id: '10',
    name: 'ESCRITURACION',
    description: 'ESCRITURACION',
    distributionPath: '',
    pathPams: '',
    pathSams: '',
    ftiiCode: '',
    conectivityType: 'Browser',
    institutionCode: '',
    isActive: true
},
{
    id: '20',
    name: 'ALZAMIENTO',
    description: 'ALZAMIENTO',
    distributionPath: '',
    pathPams: '',
    pathSams: '',
    ftiiCode: '',
    conectivityType: 'Browser',
    institutionCode: '',
    isActive: true
},
{
    id: '1',
    name: 'OPERACIONES',
    description: 'OPERACIONES',
    distributionPath: '',
    pathPams: '',
    pathSams: '',
    ftiiCode: '',
    conectivityType: 'Browser',
    institutionCode: '',
    isActive: true
},
{
    id: '45',
    name: 'RECURSOS HUMANOS',
    description: 'RECURSOS HUMANOS',
    distributionPath: '',
    pathPams: '',
    pathSams: '',
    ftiiCode: '',
    conectivityType: 'Browser',
    institutionCode: '',
    isActive: true
},
{
    id: '05',
    name: 'AREA 05',
    description: 'AREA 05',
    distributionPath: '',
    pathPams: '',
    pathSams: '',
    ftiiCode: '',
    conectivityType: 'Browser',
    institutionCode: '',
    isActive: true
}];