export const users = [{
        dni: '19117638',
        password: 'hola123',
        passwordExpirationDate: "2024-12-10",
        publicName: 'J. BUSTOS',
        userGroup: '05 - Administrador de Instituciones',
        userProfile: 'Administrador',
        areaCode: '05',
        location: 'Santiago',
        region: 'Region Metropolitana',
        comunne: 'Santiago',
        status: 'Active',
        email: 'jbustos@sinacofi.cl',
        institutionCode: '0016 - BCI',
    },
    {
        dni: '13442239',
        password: 'password123',
        passwordExpirationDate: "2025-01-15",
        publicName: 'LUIS PEREIRA',
        userGroup: '03 - Tratador de Mensajes',
        userProfile: 'Usuario',
        areaCode: '10',
        location: 'Valparaíso',
        region: 'Valparaíso',
        comunne: 'Viña del Mar',
        status: 'Active',
        email: 'lpereira@sinacofi.cl',
        institutionCode: '0016 - BCI',
    },
    {
        dni: '9480327',
        password: 'password123',
        passwordExpirationDate: "2025-01-15",
        publicName: 'NICOLAS ROCA',
        userGroup: '03 - Tratador de Mensajes',
        userProfile: 'Usuario',
        areaCode: '10',
        location: 'Valparaíso',
        region: 'Valparaíso',
        comunne: 'Viña del Mar',
        status: 'Active',
        email: 'nroca@sinacofi.cl',
        institutionCode: '732 - LOS ANDES TARJETAS DE PREPAGO S.A.',
    },
    {
        dni: '3077016',
        password: 'password123',
        passwordExpirationDate: "2025-01-15",
        publicName: 'DANIEL KOKAL',
        userGroup: '03 - Tratador de Mensajes',
        userProfile: 'Usuario',
        areaCode: '10',
        location: 'Valparaíso',
        region: 'Valparaíso',
        comunne: 'Viña del Mar',
        status: 'Active',
        email: 'dkokal@sinacofi.cl',
        institutionCode: '350 - HIPOTECARIA SECURITY PRINCIPAL S.A',
    },
    {
        dni: '3077015',
        password: 'password123',
        passwordExpirationDate: "2025-01-15",
        publicName: 'LUIS P. UPR1',
        userGroup: '03 - Tratador de Mensajes',
        userProfile: 'Usuario',
        areaCode: '10',
        location: 'Valparaíso',
        region: 'Valparaíso',
        comunne: 'Viña del Mar',
        status: 'Active',
        email: 'lpupri@sinacofi.cl',
        institutionCode: '732 - LOS ANDES TARJETAS DE PREPAGO S.A.',
    },
    {
        dni: '16088932',
        password: 'password123',
        passwordExpirationDate: "2025-01-15",
        publicName: 'O. VÉLIZ',
        userGroup: '05 - Administrador de Instituciones',
        userProfile: 'Administrador',
        areaCode: '05',
        location: 'Santiago',
        region: 'Region Metropolitana',
        comunne: 'Santiago',
        status: 'Active',
        email: 'oveliz@sinacofi.cl',
        institutionCode: '0016 - BCI',
    },
    {
        dni: '13003450',
        password: 'hola123',
        passwordExpirationDate: "2024-12-10",
        publicName: 'P.RAMÍREZ',
        userGroup: '03 - Tratador de Mensajes',
        userProfile: 'Usuario',
        areaCode: '10',
        location: 'Valparaíso',
        region: 'Valparaíso',
        comunne: 'Viña del Mar',
        status: 'Active',
        email: 'pramirez@sinacofi.cl',
        institutionCode: '732 - LOS ANDES TARJETAS DE PREPAGO S.A.',
    },
    {
        dni: '16642594',
        password: 'password123',
        passwordExpirationDate: "2025-01-15",
        publicName: 'JAVIER CANAL',
        userGroup: '03 - Tratador de Mensajes',
        userProfile: 'Usuario',
        areaCode: '10',
        location: 'Valparaíso',
        region: 'Valparaíso',
        comunne: 'Viña del Mar',
        status: 'Active',
        email: 'jcanal@sinacofi.cl',
        institutionCode: '732 - LOS ANDES TARJETAS DE PREPAGO S.A.',
    },
    {
        dni: '30077020',
        password: 'hola123',
        passwordExpirationDate: "2024-12-10",
        publicName: 'MONITOREO',
        userGroup: '03 - Tratador de Mensajes',
        userProfile: 'Usuario',
        areaCode: '10',
        location: 'Santiago',
        region: 'Region Metropolitana',
        comunne: 'Santiago',
        status: 'Active',
        email: 'monitoreo@sinacofi.cl',
        institutionCode: '0016 - BCI',
    },
    {
        dni: '25876655',
        password: 'hola123',
        passwordExpirationDate: "2024-12-10",
        publicName: 'LUIS TOMOCHE',
        userGroup: '03 - Tratador de Mensajes',
        userProfile: 'Usuario',
        areaCode: '10',
        location: 'Santiago',
        region: 'Region Metropolitana',
        comunne: 'Santiago',
        status: 'Active',
        email: 'ltomoche@sinacofi.cl',
        institutionCode: '0016 - BCI',
    },
    {
        dni: '12608039',
        password: 'hola123',
        passwordExpirationDate: "2024-12-10",
        publicName: 'JORGE MELEND',
        userGroup: '03 - Tratador de Mensajes',
        userProfile: 'Usuario',
        areaCode: '10',
        location: 'Santiago',
        region: 'Region Metropolitana',
        comunne: 'Santiago',
        status: 'Active',
        email: 'jmelend@sinacofi.cl',
        institutionCode: '0016 - BCI',
    },
    {
        dni: '10931215',
        password: 'hola123',
        passwordExpirationDate: "2024-12-10",
        publicName: 'BORIS RUIZ',
        userGroup: '03 - Tratador de Mensajes',
        userProfile: 'Usuario',
        areaCode: '10',
        location: 'Santiago',
        region: 'Region Metropolitana',
        comunne: 'Santiago',
        status: 'Active',
        email: 'bruiz@sinacofi.cl',
        institutionCode: '0016 - BCI',
    },
    {
        dni: '9833144',
        password: 'hola123',
        passwordExpirationDate: "2024-12-10",
        publicName: 'F.GALARCE',
        userGroup: '03 - Tratador de Mensajes',
        userProfile: 'Usuario',
        areaCode: '10',
        location: 'Santiago',
        region: 'Region Metropolitana',
        comunne: 'Santiago',
        status: 'Active',
        email: 'fgalarce@sinacofi.cl',
        institutionCode: '0016 - BCI',
    },
    {
        dni: '9077004',
        password: 'hola123',
        passwordExpirationDate: "2024-12-10",
        publicName: 'B.RUIZ ING2',
        userGroup: '03 - Tratador de Mensajes',
        userProfile: 'Usuario',
        areaCode: '10',
        location: 'Santiago',
        region: 'Region Metropolitana',
        comunne: 'Santiago',
        status: 'Active',
        email: 'bruiz@sinacofi.cl',
        institutionCode: '0016 - BCI',
    },
    {
        dni: '4077002',
        password: 'hola123',
        passwordExpirationDate: "2024-12-10",
        publicName: 'B.RUIZ OPE',
        userGroup: '03 - Tratador de Mensajes',
        userProfile: 'Usuario',
        areaCode: '10',
        location: 'Santiago',
        region: 'Region Metropolitana',
        comunne: 'Santiago',
        status: 'Active',
        email: 'bruizop@sinacofi.cl',
        institutionCode: '0016 - BCI',
    }
];