import { Data } from "./type";

export const mockData: Data[] = [
  {
    code: "05",
    name: "Area TID",
    type: "Browser",
    institutions: "Todas",
    distributionAddress: "c:/tidweb/fileserver/tams",
    pamsAddress: "c:/tidweb/fileserver/pams",
    FTAddress: "c:/tidweb/fileserver/rescateFT",
    acctions: "test1",
  },
  {
    code: "10",
    name: "TESORERIA INTEGRAL",
    type: "Browser",
    institutions: "Todas",
    distributionAddress: "c:/tidweb/fileserver/tams",
    pamsAddress: "c:/tidweb/fileserver/pams",
    FTAddress: "c:/tidweb/fileserver/rescateFT",
    acctions: "test2",
  },
  {
    code: "12",
    name: "CONTABILIDAD",
    type: "Browser",
    institutions: "Todas",
    distributionAddress: "c:/tidweb/fileserver/tams",
    pamsAddress: "c:/tidweb/fileserver/pams",
    FTAddress: "c:/tidweb/fileserver/rescateFT",
    acctions: "test3",
  },
  {
    code: "15",
    name: "PASIVOS",
    type: "Browser",
    institutions: "Todas",
    distributionAddress: "c:/tidweb/fileserver/tams",
    pamsAddress: "c:/tidweb/fileserver/pams",
    FTAddress: "c:/tidweb/fileserver/rescateFT",
    acctions: "test4",
  },
  {
    code: "20",
    name: "TARJETAS BANCARIAS",
    type: "Browser",
    institutions: "Todas",
    distributionAddress: "c:/tidweb/fileserver/tams",
    pamsAddress: "c:/tidweb/fileserver/pams",
    FTAddress: "c:/tidweb/fileserver/rescateFT",
    acctions: "test5",
  },
  {
    code: "25",
    name: "RIESGOS",
    type: "Browser",
    institutions: "Todas",
    distributionAddress: "c:/tidweb/fileserver/tams",
    pamsAddress: "c:/tidweb/fileserver/pams",
    FTAddress: "c:/tidweb/fileserver/rescateFT",
    acctions: "test6",
  },
  {
    code: "35",
    name: "CAMBIOS",
    type: "Browser",
    institutions: "Todas",
    distributionAddress: "c:/tidweb/fileserver/tams",
    pamsAddress: "c:/tidweb/fileserver/pams",
    FTAddress: "c:/tidweb/fileserver/rescateFT",
    acctions: "test7",
  },
  {
    code: "19",
    name: "Area TID",
    type: "Browser",
    institutions: "Todas",
    distributionAddress: "c:/tidweb/fileserver/tams",
    pamsAddress: "c:/tidweb/fileserver/pams",
    FTAddress: "c:/tidweb/fileserver/rescateFT",
    acctions: "test8",
  },
  {
    code: "21",
    name: "Area TID",
    type: "Browser",
    institutions: "Todas",
    distributionAddress: "c:/tidweb/fileserver/tams",
    pamsAddress: "c:/tidweb/fileserver/pams",
    FTAddress: "c:/tidweb/fileserver/rescateFT",
    acctions: "test9",
  },
  {
    code: "01",
    name: "Area TID",
    type: "Browser",
    institutions: "Todas",
    distributionAddress: "c:/tidweb/fileserver/tams",
    pamsAddress: "c:/tidweb/fileserver/pams",
    FTAddress: "c:/tidweb/fileserver/rescateFT",
    acctions: "test10",
  },
];
